project:
  type: website
  output-dir: docs

website:
  search:
      location: navbar
      type: textbox
  title: "*bio*DSC"
  navbar:    
    logo: "images/bioDSC-logo.png"
    background: "primary"
    left:
      - href: index.qmd
        text: Home
      - href: workshops.qmd
        text: Workshops
      - href: people.qmd
        text: People
      - href: blog.qmd
        text: Blog
      - href: tutorials.qmd
        text: Tutorials
      - href: further-reading.qmd
        text: Further reading
    right:
      - text: "![](/images/uva-logo.png){height=30px}"
        href: https://www.uva.nl
        target: "_blank"
  page-footer: |
    The *bio*DSC is an initiative from the University of Amsterdam  ![](/images/uva-logo.png){height=25px}

# format:
#   html:
#     theme: flatly            
#     toc: true    
#     grid:
#       sidebar-width: 300px
#       body-width: 1200px
#       margin-width: 300px
#       gutter-width: 1.5rem


format:
  html: 
    theme: flatly
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
