project:
  type: website
  resources:
    - CNAME
    - static/**
  output-dir: docs

website:
  # Uncomment the following if you want to enable the announcement bar:
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Workshop announcement** - Do you have a dataset and you don't know how to visualize it? Join our ['Bring Your Own Data' data visualisation workshop](/workshops/2025-BYOD-1.qmd) on February 24!"
  #   type: success
  #   position: below-navbar
  favicon: "images/bioDSC-without-dots-transparent.png"
  search:
      location: navbar
      type: textbox
  title: "*bio*DSC"
  navbar:    
    logo: "images/bioDSC-without-dots-transparent.png"
    background: "primary"
    left:
      - href: index.qmd
        text: Home
      - href: workshops.qmd
        text: Workshops
      - href: people.qmd
        text: People
      - text: Consultation hours
        menu:          
          - href: consultation_images.qmd
            text: \"Improve my image analysis\"
          - href: consultation_other.qmd
            text: \"Improve any analysis\"
      - href: blog.qmd
        text: Blog
      - href: tutorials.qmd
        text: Tutorials
      - href: further-reading.qmd
        text: Further reading
    right:
      - text: "![](/images/uva-logo.png){height=30px}"
        href: https://www.uva.nl
        target: "_blank"


  # sidebar:
  #   #style: "docked"
  #   search: true    
  #   contents:
  #     - section: "Sidebar"
  #       contents:
  #         - index.qmd
  #         - workshops.qmd
  #         - people.qmd
  #         - blog.qmd
  #         - tutorials.qmd
  #         - further-reading.qmd

  page-footer:
    right: "<p> <img src='/images/uva-logo.png' height=25px;> an <i>initiative</i> of the <a href='https://uva.nl' target='_blank'>University of Amsterdam </a></p>"
    
format:
  html: 
    css: styles.css
    theme: flatly
    page-layout: full
    grid:
      sidebar-width: 10px
      body-width: 700px
      margin-width: 230px
      gutter-width: 1.5rem
