project:
  type: website
  output-dir: docs

website:
  search:
      location: navbar
      type: textbox
  title: "*bio*DSC"
  navbar:    
    logo: "images/bioDSC-logo.png"
    background: "primary"
    left:
      - href: index.qmd
        text: Home
      - href: workshops.qmd
        text: Workshops
      - href: people.qmd
        text: People
      - href: blog.qmd
        text: Blog
      - href: tutorials.qmd
        text: Tutorials
      - href: further-reading.qmd
        text: Further reading
    right:
      - text: "![](/images/uva-logo.png){height=30px}"
        href: https://www.uva.nl
        target: "_blank"


  # sidebar:
  #   #style: "docked"
  #   search: true    
  #   contents:
  #     - section: "Sidebar"
  #       contents:
  #         - index.qmd
  #         - workshops.qmd
  #         - people.qmd
  #         - blog.qmd
  #         - tutorials.qmd
  #         - further-reading.qmd

  page-footer:
  
    left: "<p>an <i>initiative</i> of the <a href='https://uva.nl' target='_blank'>University of Amsterdam <img src='/images/uva-logo.png' height=25px;></a></p>"
    right: "Copyright 2024"
    

format:
  html: 
    css: styles.css
    theme: flatly
    
    
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 700px
      margin-width: 300px
      gutter-width: 1.5rem
