<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>asca_sils_answers_ab – *bio*DSC</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/bioDSC-without-dots-transparent.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5bf4af7e2e95050c9a7956e2538f3941.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/bioDSC-without-dots-transparent.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><em>bio</em>DSC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../workshops.html"> 
<span class="menu-text">Workshops</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../people.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-consultation-hours" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Consultation hours</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-consultation-hours">    
        <li>
    <a class="dropdown-item" href="../../consultation_images.html">
 <span class="dropdown-text">Improve my image analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../consultation_other.html">
 <span class="dropdown-text">Improve any analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../further-reading.html"> 
<span class="menu-text">Further reading</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.uva.nl" target="_blank"> 
<span class="menu-text"><img src="../../images/uva-logo.png" height="30"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#install-and-load-the-necessary-packages" id="toc-install-and-load-the-necessary-packages" class="nav-link active" data-scroll-target="#install-and-load-the-necessary-packages">Install and load the necessary packages</a></li>
  <li><a href="#exercise-during-lecture" id="toc-exercise-during-lecture" class="nav-link" data-scroll-target="#exercise-during-lecture">Exercise during lecture</a></li>
  <li><a href="#brassicaceae-study" id="toc-brassicaceae-study" class="nav-link" data-scroll-target="#brassicaceae-study">Brassicaceae study</a>
  <ul class="collapse">
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data Preprocessing</a></li>
  <li><a href="#linear-models-and-anova" id="toc-linear-models-and-anova" class="nav-link" data-scroll-target="#linear-models-and-anova">Linear models and ANOVA</a>
  <ul class="collapse">
  <li><a href="#two-way-crossed-anova" id="toc-two-way-crossed-anova" class="nav-link" data-scroll-target="#two-way-crossed-anova">Two-way crossed ANOVA</a></li>
  </ul></li>
  <li><a href="#asca" id="toc-asca" class="nav-link" data-scroll-target="#asca">ASCA</a></li>
  </ul></li>
  <li><a href="#additional-exercises" id="toc-additional-exercises" class="nav-link" data-scroll-target="#additional-exercises">Additional exercises</a>
  <ul class="collapse">
  <li><a href="#the-motrpac-data" id="toc-the-motrpac-data" class="nav-link" data-scroll-target="#the-motrpac-data">The MoTrPAC data</a></li>
  <li><a href="#experimental-design" id="toc-experimental-design" class="nav-link" data-scroll-target="#experimental-design">Experimental design</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">




<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Credits &amp; copyright
</div>
</div>
<div class="callout-body-container callout-body">
<p>BDA ASCA author: “Johan Westerhuis”</p>
</div>
</div>
<section id="install-and-load-the-necessary-packages" class="level1">
<h1>Install and load the necessary packages</h1>
<p>ASCA will be applied using the HDANOVA package, which also needs the mixlm package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-time installation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"mixlm"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"khliland/mixlm"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"HDANOVA"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"khliland/HDANOVA"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'lme4':
  method           from
  na.action.merMod car </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># in newer version of R you can also use pakage manager pak to install these packages</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># pak::pak("khliland/mixlm")</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># pak::pak("khliland/HDANOVA")</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># load the libraries</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mixlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'mixlm'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    glm, lm</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HDANOVA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'HDANOVA'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:mixlm':

    RMSEP</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    loadings</code></pre>
</div>
</div>
</section>
<section id="exercise-during-lecture" class="level1">
<h1>Exercise during lecture</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a simple dataset with 3 groups and 12 samples</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create response variable y and two different design matrices for the same grouping, one with reference coding and one with sum coding</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>X0 <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>) <span class="co"># not needed in calculation; Intercept is automatically calculated in lm function</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># create design matrices for reference coding and sum coding</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>Xr1 <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">ncol =</span> <span class="dv">2</span>) <span class="co"># </span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Xs1 <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># make linear models with reference coding and sum coding</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>bref <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>Xr1)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>bsum <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>Xs1)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the summary of both models</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bref)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ Xr1)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0000 -0.7500  0.0000  0.4375  1.2500 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   6.0000     0.4330  13.856 2.24e-07 ***
Xr11         -3.0000     0.6124  -4.899 0.000849 ***
Xr12         -4.2500     0.6124  -6.940 6.76e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.866 on 9 degrees of freedom
Multiple R-squared: 0.8497,
Adjusted R-squared: 0.8163 
F-statistic: 25.44 on 2 and 9 DF,  p-value: 0.0001977 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ Xs1)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.0000 -0.7500  0.0000  0.4375  1.2500 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.5833     0.2500  14.333 1.67e-07 ***
Xs11         -0.5833     0.3536  -1.650 0.133358    
Xs12         -1.8333     0.3536  -5.185 0.000575 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.866 on 9 degrees of freedom
Multiple R-squared: 0.8497,
Adjusted R-squared: 0.8163 
F-statistic: 25.44 on 2 and 9 DF,  p-value: 0.0001977 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What are the differences in interpretation?
</div>
</div>
<div class="callout-body-container callout-body">
<p>What are the estimates for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\alpha_1\)</span>, <span class="math inline">\(\alpha_2\)</span>, <span class="math inline">\(\alpha_3\)</span> in both cases?</p>
</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>For Reference coding <span class="math inline">\(\mu = 6\)</span>, <span class="math inline">\(\alpha_1 = 0\)</span>, <span class="math inline">\(\alpha_2 = -3\)</span>, <span class="math inline">\(\alpha_3 = -4.25\)</span>.</li>
<li>Reference coding forces the intercept to be equal to the groupmean of group 1. The a1 value is 0 as group 1 is the reference group.</li>
<li>For Sum coding <span class="math inline">\(\mu = 3.5833\)</span>, <span class="math inline">\(\alpha_1 = 2.4166\)</span>, <span class="math inline">\(\alpha_2 = -0.5833\)</span>, <span class="math inline">\(\alpha_3 = -1.8333\)</span>. The <span class="math inline">\(\alpha_1 = 2.4166\)</span> value can be obtained as the sum of <span class="math inline">\(\alpha_1\)</span>, <span class="math inline">\(\alpha_2\)</span> and <span class="math inline">\(\alpha_3\)</span> has to be 0. Sumcoding makes the intercept to be equal to the average of all groups. The interpretation of the effects is therefore different between Reference and Sum coding. Note however, that the full model statistics are exactly equal.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="brassicaceae-study" class="level1">
<h1>Brassicaceae study</h1>
<p>In this exercise you will use the <strong>HDANOVA</strong> and <strong>mixlm</strong> packages to explore linear models and ASCA for analysis of high dimensional data from an designed study setup.</p>
<p>Plants in the Cabbage family (Brassicaceae) make very specific defense compounds, called glucosinolates, when under attack by herbivores. There are about 120 different versions of these glucosinolates, but here we measure only 11. To simulate a herbivore attack and elicit the plant to make glucosinolates, the plant hormone jasmonic acid (JA) was applied to either the roots (Root induced) or to the leaves (Shoot induced) of cabbage plants (B. oleracea). The glucosinolate levels for 11 different glucosinolates were measured at 1, 3, 7 and 14 days after treatment. This measurement was destructive so that for each time-point different plants were analyzed. For each treatment, 5 different plants were measured at each time point. Besides the two treatments there was also a control group that received no JA treatment. We would like to know how the different treatments affect the glucosinolate composition and whether the glucosinolate composition varies with time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data and design</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"Data.csv"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>Design <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"F.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the Environment window (top right) click on Data and Design to see the content of these two sets. Data contains the measurements, and Design the experimental settings of the samples.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Is the design balanced?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Yes, each combination of Treatment and Time has 5 replicates.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What are important specifics you can observe by a quick look at the Data?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Some variables have many zeros, some variables have much higher values than others.</p>
</div>
</div>
</div>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">Data Preprocessing</h2>
<p>First make a boxplot of the data to see which preprocessing steps should be taken.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Wat problematic issues do you observe for which variables?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="line-block">Some features have few extreme large values (e.g.&nbsp;Neo, GBC), their distribution seems skewed to the right. Others have zero’s (feature 2, 6, 9 etc).</div>
<p>Sizes of the different features are also different (GBC and NEO are large).</p>
</div>
</div>
</div>
<p>In such a case a square root transform is often a good choice to preprocess the data.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Explain why a square root transform is a useful transformation for these data.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="line-block">If there is more variation between the replicates for higher values of a feature (the feature distribution is rights skewed), then a transformation can correct that.</div>
<p>If there are zero values, a log transform is problematic. A square root transform does not have problems with zero values, and makes the distributions more symmetric around the mean. A square root transform also makes the sizes of the features more equal.</p>
</div>
</div>
</div>
<p>Make a data frame containing factors Time and Treatment and Data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a data frame containing factors Time and Treatment and Data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="fu">sqrt</span>(Data),Design);</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Time <span class="ot">=</span> <span class="fu">as.factor</span>(dat<span class="sc">$</span>Time)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Treatment <span class="ot">=</span> <span class="fu">as.factor</span>(dat<span class="sc">$</span>Treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-models-and-anova" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-and-anova">Linear models and ANOVA</h2>
<p>To explore the effect of the treatments on the glucosinolates, let’s start with an ANOVA model for a single response using the lm function. By default the lm function uses SUM coding for the treatment levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make 1-way ANOVA model for PRO using Treatment as a factor</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mod_Treatment <span class="ot">=</span> <span class="fu">lm</span>(PRO<span class="sc">~</span>Treatment, <span class="at">data =</span> dat)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">anova</span>(mod_Treatment))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: PRO
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Treatment  2 1.9070 0.95350  12.279 3.677e-05 ***
Residuals 57 4.4261 0.07765                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>There is clearly a difference between the treatments as the p-value is very low. The summary command wil provide some more info on the treatment levels, and provide residual plots to check the assumptions on the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a little bit more information</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_Treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PRO ~ Treatment, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.65977 -0.16330 -0.01696  0.17395  0.70311 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.12393    0.03597  31.242  &lt; 2e-16 ***
Treatment(control) -0.23904    0.05088  -4.698  1.7e-05 ***
Treatment(root)     0.18896    0.05088   3.714 0.000466 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.2787 on 57 degrees of freedom
Multiple R-squared: 0.3011,
Adjusted R-squared: 0.2766 
F-statistic: 12.28 on 2 and 57 DF,  p-value: 3.677e-05 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_Treatment, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Explain why the effect of one of the treatment levels is not calculated. How can you obtain information about this level?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If all levels are represented in the design matrix, and the intercept is estimated as well, then there are too many free parameters leading to a situation with infinite number of solutions. By forcing the extra restriction that all treatment effect add up to 0 (which is the result of Sum coding) this situation is solved. The shoot level effect, which is not estimated, thus equals 0.05008.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is your interpretation of this model? What can you say about the root, shoot and control levels? How can you interpret the residual plots?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>The intercept is the average value of all measurements.</li>
<li>The root treatment provides PRO levels on average 0.24 lower than the average, while the shoot treatment provides PRO levels 0.19 higher than the average.</li>
<li>The control level is not indicated, but the sum of all treatment levels equals zero, thus the control level provides PRO levels around 0.05 higher than the average.</li>
<li>The root and shoot levels are clearly different from zero according to the t-test.</li>
<li>The residual vs Fitted plot shows residuals are nicely spread around zero for all fitted values (which are 1.12 - 0.24 for control; 1.12+0.05 for control and 1.12+0.19 for shoot).</li>
<li>The QQ residuals plot to check normality shows only three samples with slightly higher residuals than expected. This shows that the residuals follow a normal distribution quite well.</li>
</ul>
</div>
</div>
</div>
<section id="two-way-crossed-anova" class="level3">
<h3 class="anchored" data-anchor-id="two-way-crossed-anova">Two-way crossed ANOVA</h3>
<p>Instead of a single factor we also want to know the effect of both factors and also their interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># two-way crossed ANOVA</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(GBN <span class="sc">~</span> Time<span class="sc">*</span>Treatment, <span class="at">data =</span> dat) <span class="co"># Note the * means all main effects and interactions</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">anova</span>(mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GBN
               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
Time            3 1.43105 0.47702 12.0563 5.286e-06 ***
Treatment       2 2.53574 1.26787 32.0447 1.446e-09 ***
Time:Treatment  6 0.58878 0.09813  2.4802   0.03598 *  
Residuals      48 1.89916 0.03957                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>For GBN, we see that both factors (Time and Treatment) are significant as is their interaction. Also here check the significance of the levels of each of the factors and interaction using the summary command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GBN ~ Time * Treatment, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.50802 -0.09877  0.01176  0.14722  0.35607 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     0.72591    0.02568  28.268  &lt; 2e-16 ***
Time(Day 1)                    -0.09904    0.04448  -2.227  0.03069 *  
Time(Day 3)                    -0.03805    0.04448  -0.855  0.39653    
Time(Day 7)                    -0.12478    0.04448  -2.805  0.00724 ** 
Treatment(control)             -0.19846    0.03632  -5.465 1.63e-06 ***
Treatment(root)                 0.28322    0.03632   7.799 4.44e-10 ***
Time(Day 1):Treatment(control)  0.07388    0.06290   1.175  0.24595    
Time(Day 3):Treatment(control)  0.17012    0.06290   2.705  0.00943 ** 
Time(Day 7):Treatment(control) -0.09090    0.06290  -1.445  0.15494    
Time(Day 1):Treatment(root)    -0.10348    0.06290  -1.645  0.10648    
Time(Day 3):Treatment(root)    -0.01616    0.06290  -0.257  0.79833    
Time(Day 7):Treatment(root)     0.03650    0.06290   0.580  0.56444    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.1989 on 48 degrees of freedom
Multiple R-squared: 0.7058,
Adjusted R-squared: 0.6383 
F-statistic: 10.47 on 11 and 48 DF,  p-value: 2.007e-09 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Explain your interpretation of this model.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>For GBN there is a clear treatment effect and also some timepoints are different.</li>
<li>There is a single interaction clearly different from zero.</li>
<li>The GBN values at time 3 for the control treatment are 0.17 higher than could be expected from their main factor results control treatment effect and day 3 effect.</li>
</ul>
</div>
</div>
</div>
<p>Different codings can be used for the factors. Here you can compare sum coding and treatment (reference) coding.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Different codings</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>mod_sum <span class="ot">&lt;-</span> <span class="fu">lm</span>(GBN <span class="sc">~</span> Time<span class="sc">*</span>Treatment, <span class="at">data =</span> dat, <span class="at">contrasts =</span> <span class="st">"contr.sum"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">anova</span>(mod_sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GBN
               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
Time            3 1.43105 0.47702 12.0563 5.286e-06 ***
Treatment       2 2.53574 1.26787 32.0447 1.446e-09 ***
Time:Treatment  6 0.58878 0.09813  2.4802   0.03598 *  
Residuals      48 1.89916 0.03957                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GBN ~ Time * Treatment, data = dat, contrasts = "contr.sum")

Residuals:
     Min       1Q   Median       3Q      Max 
-0.50802 -0.09877  0.01176  0.14722  0.35607 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     0.72591    0.02568  28.268  &lt; 2e-16 ***
Time(Day 1)                    -0.09904    0.04448  -2.227  0.03069 *  
Time(Day 3)                    -0.03805    0.04448  -0.855  0.39653    
Time(Day 7)                    -0.12478    0.04448  -2.805  0.00724 ** 
Treatment(control)             -0.19846    0.03632  -5.465 1.63e-06 ***
Treatment(root)                 0.28322    0.03632   7.799 4.44e-10 ***
Time(Day 1):Treatment(control)  0.07388    0.06290   1.175  0.24595    
Time(Day 3):Treatment(control)  0.17012    0.06290   2.705  0.00943 ** 
Time(Day 7):Treatment(control) -0.09090    0.06290  -1.445  0.15494    
Time(Day 1):Treatment(root)    -0.10348    0.06290  -1.645  0.10648    
Time(Day 3):Treatment(root)    -0.01616    0.06290  -0.257  0.79833    
Time(Day 7):Treatment(root)     0.03650    0.06290   0.580  0.56444    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.1989 on 48 degrees of freedom
Multiple R-squared: 0.7058,
Adjusted R-squared: 0.6383 
F-statistic: 10.47 on 11 and 48 DF,  p-value: 2.007e-09 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod_treat <span class="ot">&lt;-</span> <span class="fu">lm</span>(GBN <span class="sc">~</span> Time<span class="sc">*</span>Treatment, <span class="at">data =</span> dat, <span class="at">contrasts =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">anova</span>(mod_treat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GBN
               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
Time            3 1.43105 0.47702 12.0563 5.286e-06 ***
Treatment       2 2.53574 1.26787 32.0447 1.446e-09 ***
Time:Treatment  6 0.58878 0.09813  2.4802   0.03598 *  
Residuals      48 1.89916 0.03957                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_treat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GBN ~ Time * Treatment, data = dat, contrasts = "contr.treatment")

Residuals:
     Min       1Q   Median       3Q      Max 
-0.50802 -0.09877  0.01176  0.14722  0.35607 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   0.502290   0.088956   5.647 8.65e-07 ***
Time(Day 3)                   0.157235   0.125803   1.250   0.2174    
Time(Day 7)                  -0.190511   0.125803  -1.514   0.1365    
Time(Day14)                   0.133920   0.125803   1.065   0.2924    
Treatment(root)               0.304319   0.125803   2.419   0.0194 *  
Treatment(shoot)              0.069405   0.125803   0.552   0.5837    
Time(Day 3):Treatment(root)  -0.008923   0.177912  -0.050   0.9602    
Time(Day 7):Treatment(root)   0.304759   0.177912   1.713   0.0932 .  
Time(Day14):Treatment(root)   0.413618   0.177912   2.325   0.0244 *  
Time(Day 3):Treatment(shoot) -0.279802   0.177912  -1.573   0.1224    
Time(Day 7):Treatment(shoot)  0.189576   0.177912   1.066   0.2920    
Time(Day14):Treatment(shoot)  0.267368   0.177912   1.503   0.1394    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

s: 0.1989 on 48 degrees of freedom
Multiple R-squared: 0.7058,
Adjusted R-squared: 0.6383 
F-statistic: 10.47 on 11 and 48 DF,  p-value: 2.007e-09 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Discuss the differences between the two types of coding. When is one preferred over the other?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The difference is mainly what is considered the intercept (base level) of the model. If a control level is present, one would like to see how the treated level is different from the control instead of how the both differ from their average.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is the interpretation of the intercept in the models? What is the meaning of the estimated coefficients in each model?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the SUM coded model, the intercept represents the overall mean, but in the treatment coding the intercept represents the mean of the Control treatment samples at time 1. Check this! The effects of the other levels mean the difference between those levels and the Control at time 1 level.</p>
</div>
</div>
</div>
</section>
</section>
<section id="asca" class="level2">
<h2 class="anchored" data-anchor-id="asca">ASCA</h2>
<p>ASCA generalizes ANOVA or the linear model to the multivariate setting. The models are applied to all response variables, and the variation due to the different factors (and their interactions) is summarized into effect matrices. Then a PCA model can be applied to each effect matrix separately of in combination to find variation that is systematic over all the variables. This variation is then summarized with PCA scores and loadings.</p>
<p>We will use the <strong>HDANOVA</strong> package to apply asca. The HDANOVA package expects to be in the long format. The next sections transforms the data from wide to long format. Furthermore, the factors Time and Treatment have to be defined as factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data from wide to long format</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>Metabolites <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Time =</span> dat<span class="sc">$</span>Time,<span class="at">Treatment =</span> dat<span class="sc">$</span>Treatment, <span class="at">Metab =</span> <span class="fu">I</span>(<span class="fu">as.matrix</span>(dat[,<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>])))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>Metabolites<span class="sc">$</span>Time <span class="ot">=</span> <span class="fu">as.factor</span>(Metabolites<span class="sc">$</span>Time)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>Metabolites<span class="sc">$</span>Treatment <span class="ot">=</span> <span class="fu">as.factor</span>(Metabolites<span class="sc">$</span>Treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then make an ASCA model of the metabolite data using both Time and Treatment as factors together with their interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ASCA model of all variables simultaneously</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>mod_asca <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metab <span class="sc">~</span> Time<span class="sc">*</span>Treatment, <span class="at">data=</span>Metabolites)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_asca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation 
               Sum.Sq. Expl.var.(%)
Time              8.22        10.22
Treatment        39.74        49.42
Time:Treatment    5.72         7.12
Residuals        26.72        33.24</code></pre>
</div>
</div>
<p>Open de mod_asca list and look at all the parameters that have been calculated. Click the scores section. The scores are calculated For each of the effect matrices. This is also the case for the loadings and Projected scores. The latter are the score values calculated with back projection, using the residuals and the effect matrices together, as discussed in the lecture.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple functions to use</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scoreplot</span>(mod_asca, <span class="at">factor=</span><span class="st">"Treatment"</span>, <span class="at">legend =</span> (<span class="st">"topright"</span>), <span class="at">main=</span><span class="st">"Treatment scores"</span>, <span class="at">projections =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scoreplot</span>(mod_asca, <span class="at">factor=</span><span class="st">"Treatment"</span>, <span class="at">legend =</span> (<span class="st">"topright"</span>), <span class="at">main=</span><span class="st">"Projected Treatment scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scoreplot</span>(mod_asca, <span class="at">factor=</span><span class="st">"Treatment"</span>, <span class="at">legend =</span> (<span class="st">"topright"</span>), <span class="at">main=</span><span class="st">"Treatment scores Spider plot"</span>, <span class="at">spider =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">loadingplot</span>(mod_asca, <span class="at">factor=</span><span class="st">"Treatment"</span>, <span class="at">scatter=</span><span class="cn">TRUE</span>, <span class="at">labels=</span><span class="st">"names"</span>, <span class="at">main=</span><span class="st">"Treatment loadings"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For more control you can obtain information from the mod_asca list, e.g. when you only want to plot the top 8 loadings</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading plot for only important loadings</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>Var_Exp_Treatment <span class="ot">=</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> mod_asca[[<span class="st">"singulars"</span>]][[<span class="st">"Treatment"</span>]]<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(mod_asca[[<span class="st">"singulars"</span>]][[<span class="st">"Treatment"</span>]]<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>P_Treatment <span class="ot">=</span> mod_asca[[<span class="st">"loadings"</span>]][[<span class="st">"Treatment"</span>]];</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>Importance <span class="ot">=</span> P_Treatment[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> P_Treatment[,<span class="dv">2</span>]<span class="sc">^</span><span class="dv">2</span>;</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>NIMP <span class="ot">=</span> <span class="dv">8</span>; <span class="co"># number of important variables</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>sorted_Importance <span class="ot">=</span> <span class="fu">sort</span>(Importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>, <span class="at">index.return =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>Importance_Index <span class="ot">=</span> sorted_Importance<span class="sc">$</span>ix[<span class="dv">1</span><span class="sc">:</span>NIMP]</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(P_Treatment[Importance_Index,<span class="dv">1</span>],P_Treatment[Importance_Index,<span class="dv">2</span>],<span class="at">type =</span> <span class="st">"n"</span>,<span class="at">xlab=</span><span class="fu">paste0</span>(<span class="st">"Comp 1 ("</span>, Var_Exp_Treatment[<span class="dv">1</span>], <span class="st">"%)"</span>), <span class="at">ylab=</span><span class="fu">paste0</span>(<span class="st">"Comp 2 ("</span>, Var_Exp_Treatment[<span class="dv">2</span>], <span class="st">"%)"</span>), <span class="at">main =</span> <span class="st">"Important Treatment loadings"</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(P_Treatment[Importance_Index,<span class="dv">1</span>],P_Treatment[Importance_Index,<span class="dv">2</span>],<span class="fu">colnames</span>(Data[,Importance_Index]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is your interpretation of the ASCA model of the Treatment factor?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>There is a clear difference between the shoot and control treatments, which are described by the 1<sup>st</sup> PC of the treatment factor. GBC and NEO have the largest contribution to this effect.</li>
<li>The 2<sup>nd</sup> PC which is much smaller wrt explained variation shows how the root treatment is different from control and shoot, and here GBN and PRO have the largest contribution. Check this by looking in the data whether this observation is correct!</li>
</ul>
</div>
</div>
</div>
<p>It is important to check whether the factors and interactions are significant. This can be done using permutation testing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>mod.perm <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metab <span class="sc">~</span> Time<span class="sc">*</span>Treatment, <span class="at">data=</span>Metabolites, <span class="at">permute =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.perm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation, 1000 permutations 
               Sum.Sq. Expl.var.(%) p-value
Time              8.22        10.22       0
Treatment        39.74        49.42       0
Time:Treatment    5.72         7.12       0
Residuals        26.72        33.24      NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod.perm, <span class="at">factor =</span> <span class="st">"Time"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod.perm, <span class="at">factor =</span> <span class="st">"Treatment"</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod.perm, <span class="at">factor =</span> <span class="st">"Time:Treatment"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What conclusion can you draw from the permutation test results?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Both factors as well as the interaction have a significant effect on the glucosinolate levels. For the main effects none of the permutations gave better results than the true grouping, while for the interaction only few permutations were larger than the true grouping.</p>
</div>
</div>
</div>
<section id="combining-main-and-interaction-effects" class="level4">
<h4 class="anchored" data-anchor-id="combining-main-and-interaction-effects">Combining Main and Interaction effects</h4>
<p>Sometimes it makes sense to combine effects, e.g., a main factor and an interaction. This is especially the case when the effect of Treatments are studied over Time. Here we combine the effects of Treatment and the Time:Treatment interaction. Note the effect matrices of Treatment and Time:Treatment are estimated independently, but the PCA is applied on the sum of these two effect matrices.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mod.comb <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metab <span class="sc">~</span> Time <span class="sc">+</span> <span class="fu">comb</span>(Treatment <span class="sc">+</span> Time<span class="sc">:</span>Treatment), <span class="at">data=</span>Metabolites)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod.comb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation 
                         Sum.Sq. Expl.var.(%)
Time                        8.22        10.22
Treatment+Time:Treatment   45.47        56.54
Residuals                  26.72        33.24</code></pre>
</div>
</div>
<p>If combined effects have a Time factor, the scores can be plotted against the time using the timeplot function. For this plot the legend command has to be called separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">timeplot</span>(mod.comb, <span class="at">factor=</span><span class="st">"Treatment"</span>, <span class="at">time=</span><span class="st">"Time"</span>, <span class="at">comb=</span><span class="dv">2</span>, <span class="at">comp=</span><span class="dv">1</span>,  <span class="at">x_time=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in timeplot(mod.comb, factor = "Treatment", time = "Time", comb = 2, :
NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,<span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="fu">levels</span>(Metabolites<span class="sc">$</span>Treatment))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">loadingplot</span>(mod.comb, <span class="at">factor =</span> <span class="st">"Treatment+Time:Treatment"</span>, <span class="at">comp=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Give your interpretation of this combined effect.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the scoreplot we see the combined effect of Treatment and Time:Treatment interaction. This shows that the effect of the treatments is not constant over time. The biological explanation is that both root and shoot treatments have an effect, but after day 3, the root effect disappears and the glucosinolate levels go back to the control values. The shoot effect however is consistent and even increases over time. Variables 8 (GBC) and 11 (NEO) are largely effected by these treatment differences.</p>
</div>
</div>
</div>
<p>Finally, it can be useful to also explore the residual matrix to see whether there are effects in the data that is not modeled for.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make score and loading plots and interpret.</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">loadingplot</span>(mod.comb, <span class="at">factor=</span><span class="st">"Residuals"</span>, <span class="at">scatter=</span><span class="cn">TRUE</span>, <span class="at">labels=</span><span class="st">"names"</span>, <span class="at">main=</span><span class="st">"Residual loadings"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scoreplot</span>(mod.comb, <span class="at">factor=</span><span class="st">"Residuals"</span>, <span class="at">main=</span><span class="st">"Residual scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Why is it useful to also explore the residuals and interpret the PCA model of the residuals.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can see that some plants (the cluster bottom right deviate from the main group. These will have higher values of NEO and lower values of GBC than the other plants.)</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="additional-exercises" class="level1">
<h1>Additional exercises</h1>
<p>In this 2<sup>nd</sup> exercise you have to do some coding yourself. Look at the code provided above to see how to use the functions.</p>
<section id="the-motrpac-data" class="level3">
<h3 class="anchored" data-anchor-id="the-motrpac-data">The MoTrPAC data</h3>
<p>The Molecular Transducers of Physical Activity Consortium (MoTrPAC) profiled the dynamic change of multiple omics layers in several organs of rats undergoing physical training. The results are presented in the Nature article “Temporal dynamics of the multi-omic response to endurance exercise training”. <a href="https://www.nature.com/articles/s41586-023-06877-w" class="uri">https://www.nature.com/articles/s41586-023-06877-w</a> The data was obtained from their website MoTrPAC-data.org.</p>
</section>
<section id="experimental-design" class="level3">
<h3 class="anchored" data-anchor-id="experimental-design">Experimental design</h3>
<p>Six-month-old male and female Fischer 344 rats were subjected to progressive treadmill endurance exercise training for 1, 2, 4 or 8 weeks. Sex-matched sedentary, untrained rats were used as controls (0). In this application we will focus on metabolomics data from plasma. Unfortunately these measurements do not all come from the same rats. Note that Females have Sex = 1 and Males have Sex = 2.</p>
<section id="load-and-view-the-data" class="level4">
<h4 class="anchored" data-anchor-id="load-and-view-the-data">Load and view the data</h4>
<p>Load the metabolomics_Values (Data) and the metabolomics_Exp (Design) files. For visualization reasons we will only select the lipids subset.</p>
<p>As preprocessing we decided to not use a transformation of the data, but only use meancentering and scaling by the standard deviation of the lipid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data and design</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>df_metabolomics_Values <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"Plasma_Metabolomics_Values_ab.csv"</span>, <span class="at">row.names=</span><span class="dv">1</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>df_metabolomics_Exp <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"Plasma_Metabolomics_Exp_ab.csv"</span>, <span class="at">row.names=</span><span class="dv">1</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>df_metabolomics_Lipids <span class="ot">=</span> df_metabolomics_Values[,<span class="dv">80</span><span class="sc">:</span><span class="dv">613</span>]</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co"># make boxplots of the data before preprocessing</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)) </span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df_metabolomics_Lipids)</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Preprocess the data by centering and scaling </span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>CData <span class="ot">=</span> <span class="fu">scale</span>(df_metabolomics_Lipids, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>SData <span class="ot">=</span> <span class="fu">scale</span>(df_metabolomics_Lipids, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Make boxplots of the data after centering and scaling</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(CData)</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Why did we preprocess the lipids data this way?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>From the 1<sup>st</sup> boxplot we see that the Lipids data is not centered.</li>
<li>We can also see the distributions are not skewed but rather symmetrical around their mean, thus transformation is not necessary.</li>
<li>Scaling seems necessary as the ranges of the centered data are rather different for some metabolites.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="data-handling" class="level4">
<h4 class="anchored" data-anchor-id="data-handling">Data handling</h4>
<p>Just as above the data has to be made in the long format to be able to use the <strong>HDANOVA</strong> package. Make sure the factors Sex and Group are defined as factors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make the data frame in long format</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>Data_Values_long <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Sex =</span> <span class="fu">as.factor</span>(df_metabolomics_Exp<span class="sc">$</span>Rat.Sex), <span class="at">Training =</span> <span class="fu">as.factor</span>(df_metabolomics_Exp<span class="sc">$</span>Group), <span class="at">Metabolites =</span> <span class="fu">I</span>(<span class="fu">as.matrix</span>(SData)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="asca-model-of-main-factors" class="level4">
<h4 class="anchored" data-anchor-id="asca-model-of-main-factors">ASCA model of main factors:</h4>
<p>Create an ASCA model using the only the main factors Sex and Training. Do not consider interaction terms yet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ASCA model of main factors</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>mod_asca1 <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metabolites <span class="sc">~</span> Sex <span class="sc">+</span> Training, <span class="at">data=</span>Data_Values_long)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the summary of the model</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_asca1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation 
           Sum.Sq. Expl.var.(%)
Sex       11833.23        45.22
Training   3348.41        12.80
Residuals 10984.36        41.98</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Explain the meaning of Sum.Sq and Expl.var. What is your interpretation of the ASCA model?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Sum.Sq is the sum of squares of the effect matrix, calculated by squaring each element in the effect matrix and then adding all these values.</li>
<li>Expl.var is the percentage explained variation from the total variation in the Metabolites data. It is calculated by dividing the Sum.Sq of a factor (e.g.&nbsp;Sex) by the Sum.Sq of the original data (Metabolites).</li>
<li>There is a strong effect for factor Sex and a smaller effect for factor Training.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="visualization" class="level4">
<h4 class="anchored" data-anchor-id="visualization">Visualization</h4>
<p>Make score plots of the Training effect</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Show a score plot of the Training effect.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code for a score plots of the Training effect.</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scoreplot</span>(mod_asca1, <span class="at">factor=</span><span class="st">"Training"</span>, <span class="at">legend =</span> (<span class="st">"bottomleft"</span>), <span class="at">main=</span><span class="st">"Projected Treatment scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Below the loading plots of PC1 vs PC2 of the Training factor is given. For visualization reasons we only show the most important variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading plot of only 20 most important metabolites</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># determine explained variance per principal component </span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>Var_Exp_Training <span class="ot">=</span> <span class="dv">100</span><span class="sc">*</span>(mod_asca1[[<span class="st">"singulars"</span>]][[<span class="st">"Training"</span>]]<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">sum</span>(mod_asca1[[<span class="st">"singulars"</span>]][[<span class="st">"Training"</span>]]<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>Var_Exp_Training <span class="ot">=</span> <span class="fu">round</span>(Var_Exp_Training,<span class="dv">0</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="co"># extract loadings of the Training factor</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>P_Training <span class="ot">=</span> mod_asca1[[<span class="st">"loadings"</span>]][[<span class="st">"Training"</span>]];</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the loadings of PC1 and PC2 into an importance value</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>Importance <span class="ot">=</span> <span class="fu">sqrt</span>(P_Training[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> P_Training[,<span class="dv">2</span>]<span class="sc">^</span><span class="dv">2</span>);</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>NIMP <span class="ot">=</span> <span class="dv">7</span>; <span class="co"># number of important variables</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="co"># sort the importance values and get the index of the top 20 most important variables</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>sorted_Importance <span class="ot">=</span> <span class="fu">sort</span>(Importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>, <span class="at">index.return =</span> <span class="cn">TRUE</span>)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>Importance_Index <span class="ot">=</span> sorted_Importance<span class="sc">$</span>ix[<span class="dv">1</span><span class="sc">:</span>NIMP]</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the most important variables in the loading plot</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(P_Training[Importance_Index,<span class="dv">1</span>],P_Training[Importance_Index,<span class="dv">2</span>],<span class="at">xlab=</span><span class="fu">paste0</span>(<span class="st">"Comp 1 ("</span>, Var_Exp_Training[<span class="dv">1</span>], <span class="st">"%)"</span>), <span class="at">ylab=</span><span class="fu">paste0</span>(<span class="st">"Comp 2 ("</span>, Var_Exp_Training[<span class="dv">2</span>], <span class="st">"%)"</span>))</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(P_Training[Importance_Index,<span class="dv">1</span>],P_Training[Importance_Index,<span class="dv">2</span>],<span class="fu">colnames</span>(df_metabolomics_Lipids[,Importance_Index]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_metabolomics_Lipids[,Importance_Index])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LPC.17.1.0.0._feature2"                      
[2] "LPC.14.0.0.0._and_LPC.0.0.14.0._feature1and2"
[3] "LPC.18.1.0.0._feature2"                      
[4] "LPC.20.3._feature1and2"                      
[5] "LPC.16.1.0.0._and_LPC.0.0.16.1._feature1and2"
[6] "PC.42.8._feature3"                           
[7] "LPC.18.2.0.0._feature2"                      </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Give your interpretation of the score and loading plots. [1]
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The scoreplot shows the group average of the 5 training groups by the solid marker, while the individual rats are indicated with the open markers. Component 1 mainly makes a distinction between Training week1 and week2 on the right and the control (0), 4 and 8 weeks training samples are mainly on the left part of the plot. PC2 makes a distinction between Control and 8 weeks of training. The training groups are not well separated, however the upper left part seems to be mainly related to 8 weeks of training.</p>
<p>The upper left extreme loadings (LPC17.1.0.0_feature2 and LPC14.0.0.0_andLPC0.0.14.0_feature1and2) both have high values for 8 weeks of training.</p>
</div>
</div>
</div>
</section>
<section id="asca-model-with-interaction" class="level4">
<h4 class="anchored" data-anchor-id="asca-model-with-interaction">ASCA model with interaction</h4>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Make a new model in which the two-factor interaction Sex:Training is also included in the model.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write the code for an ASCA model including main factors and interaction</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>mod_asca_Int <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metabolites <span class="sc">~</span> Sex<span class="sc">*</span>Training, <span class="at">data=</span>Data_Values_long)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Provide the summary of the model</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_asca_Int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation 
              Sum.Sq. Expl.var.(%)
Sex          11833.23        45.22
Training      3348.41        12.80
Sex:Training  2019.41         7.72
Residuals     8964.95        34.26</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is your conclusion of this ASCA model with interaction?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="line-block">The interaction explains an additional 7.7% of the variation in the data.</div>
<p>This means that the Time effect is somewhat different for males compared to females.</p>
</div>
</div>
</div>
</section>
<section id="statistical-inference" class="level4">
<h4 class="anchored" data-anchor-id="statistical-inference">Statistical Inference</h4>
<p>To conclude whether the main factors and interaction are significant, apply a permutation test and plot the permutation result using the permutation plot function for both main factors and the interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Permutation test for the ASCA model with interaction</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>mod_asca_Int_perm <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metabolites <span class="sc">~</span> Sex <span class="sc">+</span> Training <span class="sc">+</span> Sex<span class="sc">:</span>Training, <span class="at">data=</span>Data_Values_long, <span class="at">permute =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_asca_Int_perm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation, 1000 permutations 
              Sum.Sq. Expl.var.(%) p-value
Sex          11833.23        45.22       0
Training      3348.41        12.80       0
Sex:Training  2019.41         7.72       0
Residuals     8964.95        34.26      NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make permutation plots for the main factors and the interaction</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod_asca_Int_perm, <span class="at">factor =</span> <span class="st">"Sex"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod_asca_Int_perm, <span class="at">factor =</span> <span class="st">"Training"</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">permutationplot</span>(mod_asca_Int_perm, <span class="at">factor =</span> <span class="st">"Sex:Training"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: Explain why in ASCA a permutation test is used and not an F-test.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The F-statistic assumes normally distributed data and also requires the degrees of freedom for each effect. We have not tested the normality of the data, and degrees of freedom is unclear in the multivariate situation.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is your interpretation of the permutation test?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The p-value for both the Sex factor and Training factor as well as for the interaction 0, meaning that none of the permutations provides a better result than the original. This can also be seen in the permutation plots. The conclusion is that the Sex levels (Male and Female) are different from eachother and also the training group levels and that the interactions are not 0, and thus have to be included in the model.</p>
</div>
</div>
</div>
<p>Finally we can make a plot of the combination Training + Sex:Training to visualize how the Females and Males deviate in their training effect. For this we:</p>
<ol type="1">
<li>Make ASCA model in which the Sex:Training interaction effect is combined with the main Training effect.</li>
<li>Determine the explained variance of the components in combination effect.</li>
<li>Make a score plot (using the timeplot function) of the combination effect. The PC1 scores of the Females and Males are plotted as a function of the training groups.</li>
<li>Make a loading plot for PC1 of the combination effect.</li>
<li>Also show a plot of only the interaction.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1. Make Model with main factor Sex and combination of Group and Sex:Group interaction</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>mod_comb1 <span class="ot">&lt;-</span> <span class="fu">asca</span>(Metabolites <span class="sc">~</span> Sex <span class="sc">+</span> <span class="fu">comb</span>(Training<span class="sc">+</span>Sex<span class="sc">:</span>Training), <span class="at">data=</span>Data_Values_long)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_comb1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Simultaneous Component Analysis fitted using 'lm' (Linear Model) 
- SS type II, sum coding, restricted model, least squares estimation 
                       Sum.Sq. Expl.var.(%)
Sex                   11833.23        45.22
Training+Sex:Training  5367.82        20.51
Residuals              8964.95        34.26</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2.  determine explained variance of the combination effect</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>Var_Exp_Comb1 <span class="ot">=</span> <span class="dv">100</span><span class="sc">*</span>(mod_comb1[[<span class="st">"singulars"</span>]][[<span class="st">"Training+Sex:Training"</span>]]<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">sum</span>(mod_comb1[[<span class="st">"singulars"</span>]][[<span class="st">"Training+Sex:Training"</span>]]<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>Var_Exp_Comb1<span class="ot">=</span> <span class="fu">round</span>(Var_Exp_Comb1,<span class="dv">0</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co">#3.</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="fu">timeplot</span>(mod_comb1, <span class="at">factor=</span><span class="st">"Sex"</span>, <span class="at">time=</span><span class="st">"Training"</span>, <span class="at">comb=</span><span class="dv">2</span>, <span class="at">comp=</span><span class="dv">1</span>,  <span class="at">x_time=</span><span class="cn">TRUE</span>, <span class="at">ylab=</span><span class="fu">paste0</span>(<span class="st">"PC1 ("</span>, Var_Exp_Comb1[<span class="dv">1</span>], <span class="st">"%)"</span>))</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,<span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="fu">levels</span>(Data_Values_long<span class="sc">$</span>Sex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">loadingplot</span>(mod_comb1, <span class="at">factor =</span> <span class="st">"Training+Sex:Training"</span>, <span class="at">comp=</span><span class="dv">1</span>,<span class="at">ylab=</span><span class="fu">paste0</span>(<span class="st">"PC1 ("</span>, Var_Exp_Comb1[<span class="dv">1</span>], <span class="st">"%)"</span>), <span class="at">main =</span> (<span class="st">"Loadings Combination (Training+Sex:Training)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#5</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>Var_Exp_Int_Int<span class="ot">=</span> <span class="fu">round</span>(mod_asca_Int_perm[[<span class="st">"singulars"</span>]][[<span class="st">"Sex:Training"</span>]],<span class="dv">0</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">loadingplot</span>(mod_asca_Int_perm, <span class="at">factor =</span> <span class="st">"Sex:Training"</span>, <span class="at">comp=</span><span class="dv">1</span>,<span class="at">ylab=</span><span class="fu">paste0</span>(<span class="st">"PC1 ("</span>, Var_Exp_Int_Int[<span class="dv">1</span>], <span class="st">"%)"</span>),<span class="at">main =</span> (<span class="st">"Loadings Interaction Sex:Training"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ASCA_SILS_answers_ab_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Question: What is your interpretation of the combination effect (Training + Sex:Training), and of the interaction Sex:Training
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>The combination is significant (both factor Training and Sex:Training are significant).</li>
<li>Its scoreplot shows a Training time trend for each Sex.</li>
<li>Variation between the Training groups is somewhat larger for females than for males.</li>
<li>The metabolite levels change rapidly between 2 weeks and 4 weeks of training.</li>
<li>Note the differences between the loading plots for the combination and the interaction. The loading plot for the interaction only focuses on the difference between Females and Males, while the combination loadings combine the Main training variation with this difference between Females and Males. This results in different important features.</li>
</ul>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>
<img src="../../images/uva-logo.png" height="25px;"> an <i>initiative</i> of the <a href="https://uva.nl" target="_blank">University of Amsterdam </a>
</p>
</div>
  </div>
</footer>




</body></html>