---
title: "April 30 (2026): Analysis of Variance for high-dimensional data using ASCA"
date: 2026-03-19
author: Frans van der Kloet
description: "An introduction to Analysis of Variance for high-dimensional data using ASCA"
categories: [upcoming]
---

Together with the Biosystems Data Analysis group we organize a workshop on the analysis of variance for high-dimensional data using ASCA for a group of up to 24 participants. 

### Workshop goals

After this workshop you will be familiar with the basic theory of high-dimensional ANOVA. We will discuss and let you practice on: 

1. Theory of ANOVA, linear models, experimental design and principal component analysis 

2. Using R to

    * Preprocess of high-dimensional data 
    * Calculate the effect size of different experimental factors of the experiment 
    * Visualize the high-dimensional treatment effect 
    * Validate the high-dimensional treatment effect 

The practice uses a standard dataset in which cabbage plants (brassiciceae) were subjected to Jasmonic Acid on their roots and on their shoot to mimic an herbivore attack. 11 different plant hormones were measured of these plants after 1, 3, 7 and 14 days to study the plant response to the attack.  

If you have another high dimensional dataset that has a clear underlying experimental design, there is also room in the program to discuss that. Please contact us ([j.a.westerhuis@uva.nl](mailto:j.a.westerhuis@uva.nl) or [f.m.vanderkloet@uva.nl](mailto:f.m.vanderkloet@uva.nl)) in advance if you want to bring your own dataset. We can then prepare the necessary R markdown documents to analyze your dataset and dicuss the results during the workshop.

### Workshop materials

All materials required for this workshop can be found [here](/workshop-materials/bda-anova/ASCA_SILS_ab.qmd){target="_blank"}. 

### Requirements

- Good R-skills are not necessary but this workshop assumes **some basic knowledge of R and RStudio**. 
- We have installed R in a cloud environment, so you can use your browser to access R and RStudio. However, if you want to install R and RStudio on your own laptop, do this in advance, there is no time during the workshop to do so. You can follow the instructions on the [R website](https://www.r-project.org/){target="_blank"} and the RStudio [website](https://www.rstudio.com/products/rstudio/download/){target="_blank"}. Make sure that you also download the workshop markdown and install the necessary R packages. 
- You have to bring your own laptop.

### Workshop logistics

The workshop will be given by Johan Westerhuis and consists of a lecture for half of the time and hands-on exercises for the other half. You have to bring your own laptop. We will use R markdown documents to go through all the necessary steps in the calculations. 

| When:  April 30 (Thursday) 13:00 - 17:00 
Where: SP TBA
 
 
### Sign up

Sign-up [here](https://forms.office.com/e/rRi1C1Pp3q){target="_blank"}. The number of participants is limited to 24.

**deadline: 20th of April. First come, first serve.**


### Identifier

This meeting's identifier: 2026-04-30-UvA-bioDSC-BDA.

