---
title: "March 2 and 4 (2026): Introduction to RNA-seq"
date: 2026-03-02
author: Misha Paauw
description: "Learn the basics of RNA-seq analysis: from read mapping to volcano plots"
categories: [upcoming]
---

The *bio*DSC organizes an introductory workshop that will cover the basics of RNA-sequencing analysis. Note that this is a newly developed workshop. Therefore, we limit participation to **5** people for this workshop, and a super smooth experience is not guaranteed. 

### Workshop goals

After this workshop, you should be able to:

- Identify good practices when designing a RNA-Seq experiment
- Assess the quality of RNA-seq sequencing data (“reads”) using the command-line instructions
- Align RNA-seq reads to a reference genome using a splice-aware aligner (e.g. STAR).
- Generate a count matrix from the RNA-seq data alignment
- Perform a QC of your experiment through Principal Component Analysis (PCA) and sample clustering.
- Execute a differential gene expression analysis using R and the DESeq2 package.
- Be able to create key plots: volcano plot, heatmap and clustering of differentially expressed genes.

### Workshop materials

All materials required for this workshop can be found on [the workshop website](https://mishapaauw.github.io/RNA-seq-workshop/). Feel free to explore the workshop website to discover whether this workshop fits your needs. 

### Requirements

- This workshop assumes **some basic knowledge of R and RStudio**. For example, you should know how to import data tables, and make simple figures. If you're unsure about this, ask [a bioDSC member](../people.qmd).
- This workshop also assumes some basic knowledge of general molecular biology.
- You have to bring your own laptop.

### Workshop logistics

The course will be given by Misha Paauw and Martijn Wehrens from the *bio*DSC. You have to bring your own laptop. We will use a Google Notebook for the bioinformatics part of the workshop, for this you don't have to install anything. For the RStudio part of the workshop, you will need a working installation of `R`, `RStudio`, and a number of packages. Please see the [setup](https://mishapaauw.github.io/RNA-seq-workshop/episodes/01-setup.html) page of the workshop materials and make sure you complete the installation *before* the workshop starts.

### Workshop schedule

| Date | Time | Location | Topic |
| ---- | ---- | ----  | ---------- |
| March 2 (Mon) | 13:00 - 17:00 | SP B0.209 | Experimental considarations and read mapping |
| March 4 (Wed) | 13:00 - 17:00 | SP B0.208 | Differential gene expression and enrichment analysis | 

### Sign up

Because this is the first round of a newly developed workshop, we limit the number of participants to **5**. Sign up by sending an e-mail to Misha: `m.m.paauw@uva.nl`.

**Sign up deadline: 16th of February. First come, first serve.**

<!--
::: {.callout-important}
## This workshop is full.

12 people have registered, we do not have place for more participants. Unfortunately, you cannot register any more.

Please send us an [email](mailto:info@biodsc.nl) in case you were interested in signing up, such that we know to organize more workshops soon.
:::
-->

### Identifier

This meeting's identifier: 2026-03-02-UvA-bioDSC.

