::: {.callout-note}
## Note
Most questions originate from the carpentry lesson ["Plotting and Programming in Python"](http://swcarpentry.github.io/python-novice-gapminder/)
:::
---

# Exercises Lesson 14, Looping over data

### Determining Matches

::: {.callout-tip icon='false'}
## Question A
Which of these files is *not* matched by the expression glob.glob('data/*as*.csv')?

```
1. data/gapminder_gdp_africa.csv
2. data/gapminder_gdp_americas.csv
3. data/gapminder_gdp_asia.csv
```
:::

::: {.callout-caution collapse='true' icon='false'}
## Answer
1 is not matched by the glob.
:::

### Minimum File Size
::: {.callout-tip icon='false'}
## Question B

Modify this program so that it prints the number of records in the file that has the fewest records.

```python
import glob
import pandas as pd
fewest = ____
for filename in glob.glob('data/*.csv'):
    dataframe = pd.____(filename)
    fewest = min(____, dataframe.shape[0])
print('smallest file has', fewest, 'records')
```

Note that the DataFrame.shape() method returns a tuple with the number of rows and columns of the data frame.

:::

::: {.callout-caution collapse='true' icon='false'}
## Answer
```python
import glob
import pandas as pd
fewest = float('Inf')
for filename in glob.glob('data/*.csv'):
    dataframe = pd.read_csv(filename)
    fewest = min(fewest, dataframe.shape[0])
print('smallest file has', fewest, 'records')
```
:::


---

# Additional Exercises

### Comparing Data

::: {.callout-tip icon='false'}
## Question C
Write a program that reads in the regional data sets and plots the average GDP per capita for each region over time in a single chart. 

*Hint*: Pandas will raise an error if it encounters non-numeric columns in a dataframe computation so you may need to either filter out those columns or tell pandas to ignore them.

:::

::: {.callout-caution collapse='true' icon='false'}
## Answer

:::